# Generated by Django 4.2 on 2023-04-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=225)),
                ('stock', models.IntegerField(max_length=2083)),
                ('image_urls', models.CharField(max_length=2083)),
            ],
        ),
    ]
